//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationInired.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marker()
        {
            this.Comentarios = new HashSet<Comentarios>();
            this.Fotos_Marker1 = new HashSet<Fotos_Marker>();
        }
    
        public int id_marker { get; set; }
        public string nombre { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public string ubicacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> nota { get; set; }
        public string comentarios_marker { get; set; }
        public string fotos_marker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotos_Marker> Fotos_Marker1 { get; set; }
    }
}
